# Puerto del servidor
server.port=8080

# Nombre de la aplicacion
spring.application.name=catalogo-musica

# Tamano maximo de archivos subidos (MP3 e imagenes)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Nivel de logs
logging.level.org.springframework.web=INFO
